//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-messages-SSD_SERVICE_ID_sd_hebxVU7E4NfTBifC
import { messages as SSD_SERVICE_ID_sd_hebxVU7E4NfTBifC } from './sd-services/messages/messages';
//CORE_REFERENCE_IMPORT-Auth-SSD_SERVICE_ID_sd_qcsHvGUKUKU7RTSL
import { Auth as SSD_SERVICE_ID_sd_qcsHvGUKUKU7RTSL } from './sd-services/Auth';

export const UserRoutes = [
    //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-messages-SSD_SERVICE_ID_sd_hebxVU7E4NfTBifC
SSD_SERVICE_ID_sd_hebxVU7E4NfTBifC,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-Auth-SSD_SERVICE_ID_sd_qcsHvGUKUKU7RTSL
SSD_SERVICE_ID_sd_qcsHvGUKUKU7RTSL,
];
